# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/widget_video.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoFrame(object):
    def setupUi(self, VideoFrame):
        VideoFrame.setObjectName("VideoFrame")
        VideoFrame.resize(815, 641)
        VideoFrame.setStyleSheet("QFrame{\n"
"    background-color:rgb(179, 170, 200);\n"
"    border-radius: 15px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(VideoFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(VideoFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.videoLabel.setFont(font)
        self.videoLabel.setScaledContents(True)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout.addWidget(self.videoLabel)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(VideoFrame)
        QtCore.QMetaObject.connectSlotsByName(VideoFrame)

    def retranslateUi(self, VideoFrame):
        _translate = QtCore.QCoreApplication.translate
        VideoFrame.setWindowTitle(_translate("VideoFrame", "Form"))
        self.videoLabel.setText(_translate("VideoFrame", "Video Will be There"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoFrame = QtWidgets.QWidget()
    ui = Ui_VideoFrame()
    ui.setupUi(VideoFrame)
    VideoFrame.show()
    sys.exit(app.exec_())
