# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/widget_light_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LightControl(object):
    def setupUi(self, LightControl):
        LightControl.setObjectName("LightControl")
        LightControl.resize(300, 300)
        LightControl.setStyleSheet("QFrame{\n"
"    background-color:rgb(179, 170, 200);\n"
"    border-radius: 15px;}")
        self.gridLayout = QtWidgets.QGridLayout(LightControl)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(LightControl)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LightControlFrame = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LightControlFrame.setFont(font)
        self.LightControlFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.LightControlFrame.setObjectName("LightControlFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LightControlFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.visibleCBox_1 = QtWidgets.QCheckBox(self.LightControlFrame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.visibleCBox_1.setFont(font)
        self.visibleCBox_1.setAutoExclusive(False)
        self.visibleCBox_1.setObjectName("visibleCBox_1")
        self.verticalLayout_2.addWidget(self.visibleCBox_1)
        self.visibleCBox_2 = QtWidgets.QCheckBox(self.LightControlFrame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.visibleCBox_2.setFont(font)
        self.visibleCBox_2.setObjectName("visibleCBox_2")
        self.verticalLayout_2.addWidget(self.visibleCBox_2)
        self.redCBox = QtWidgets.QCheckBox(self.LightControlFrame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.redCBox.setFont(font)
        self.redCBox.setObjectName("redCBox")
        self.verticalLayout_2.addWidget(self.redCBox)
        self.infraredCBox = QtWidgets.QCheckBox(self.LightControlFrame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.infraredCBox.setFont(font)
        self.infraredCBox.setObjectName("infraredCBox")
        self.verticalLayout_2.addWidget(self.infraredCBox)
        self.ultravioletCBox = QtWidgets.QCheckBox(self.LightControlFrame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(10)
        self.ultravioletCBox.setFont(font)
        self.ultravioletCBox.setTristate(False)
        self.ultravioletCBox.setObjectName("ultravioletCBox")
        self.verticalLayout_2.addWidget(self.ultravioletCBox)
        self.verticalLayout.addWidget(self.LightControlFrame)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(LightControl)
        QtCore.QMetaObject.connectSlotsByName(LightControl)

    def retranslateUi(self, LightControl):
        _translate = QtCore.QCoreApplication.translate
        LightControl.setWindowTitle(_translate("LightControl", "Form"))
        self.LightControlFrame.setTitle(_translate("LightControl", "Light Control"))
        self.visibleCBox_1.setText(_translate("LightControl", "Visible 1"))
        self.visibleCBox_2.setText(_translate("LightControl", "Visible 2"))
        self.redCBox.setText(_translate("LightControl", "Red"))
        self.infraredCBox.setText(_translate("LightControl", "Infra Red"))
        self.ultravioletCBox.setText(_translate("LightControl", "Ultra Violet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LightControl = QtWidgets.QWidget()
    ui = Ui_LightControl()
    ui.setupUi(LightControl)
    LightControl.show()
    sys.exit(app.exec_())
